name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zephyr project
        uses: zmkfirmware/zmk-action-setup@v2

      - name: Build Saphira UF2
        uses: zmkfirmware/zmk-action-build@v2
        with:
          keymap: saphira
          shield: saphira
          board: nice_nano_v2

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: saphira-firmware
          path: build/zephyr/zmk.uf2
