name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ZMK UF2
        uses: petejohnston/zmk-builder@main
        with:
          board: nice_nano_v2
          shield: saphira

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: saphira-firmware
          path: build/zephyr/zmk.uf2
